# Generated by Django 4.1 on 2024-07-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photopost',
            old_name='Category',
            new_name='category',
        ),
    ]
